feder-cr/Jobs_Applier_AI_Agent_AIHawk

README.md

Reverts feder-cr/linkedIn_auto_jobs_applier_with_AI#17

Revert "Apologies, the spelling of Italy was upsetting me"

---

setup.bat
setup.sh

For Windows: Double-click or run setup.bat in the command prompt
For Linux/macOS: Run setup.sh in the terminal with the command: bash setup.sh
Check and Installs all the dependencies, requirements before running the project. Makes it easier for users to use it.
The script installs the webdriver-manager Python package, which automatically manages the ChromeDriver binary required for Selenium.

Crossplatform automated setup using bash and batch filed

---

src/strings.py

chore: update strings.py

---

README.md
src/gpt.py

This will add a link to the tutorial video and adjust the LLM temperature to reduce hallucinations.

Update readme and gpt.py

---

README.md

PR to upd default main branch similar as V3

Readme upd to ease troubleshooting and fixing

---

src/linkedin-api.py

Added few instructions to apply_jobs function toDo, if you want to contribute please follow the instructions and ask for help if needed.

Instructions to apply_jobs function toDo

---

main.py

It was giving me "UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2810: character maps to <undefined>" error after some lookaround implementing character encoding solved the issue. Not sure if I should raise a PR but yet I thought if someone else has the issue, this should fix it.

Added Encoding for Unicode

---

src/linkedin-api.py

Fixed method to search jobs, setting none as default value.

Fix for search method

---

README.md
requirements.txt
src/gpt.py

Added GeminiModel class with its import, updated requirements.txt and README.txt.

Adding Google Gemini Implementation

---

pytest.ini
requirements.txt
src/linkedIn_easy_applier.py
tests/test_job_application_profile.py
tests/test_linkedIn_authenticator.py
tests/test_linkedIn_bot_facade.py
tests/test_linkedIn_easy_applier.py
tests/test_linkedIn_job_manager.py
tests/test_utils.py

This pull request introduces comprehensive unit tests for the `LinkedInJobManager` class to improve test coverage and ensure the robustness of the job application process. Additionally, several fixes were made to enhance error handling and ensure smooth operation when dealing with mocked objects.
---
1. **Unit Tests for `LinkedInJobManager`:**
- Added unit tests for the following methods:
- `set_parameters`
- `next_job_page`
- `get_jobs_from_page`
- `apply_jobs`
- Mocked various components to simulate job search pages, job listings, and job applications.
- Ensured that tests can be run without real file I/O by mocking file operations.
2. **Mocking File System Interactions:**
- Introduced mocking for file operations using `mock_open` to simulate writing JSON files (job application …

Add Unit Tests for LinkedInJobManager

---

main.py

The same changes as in https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/452 but for v4 branch

fix: ask resume style with only when resume flag is not provided

---

assets/resume_schema.yaml
data_folder/config.yaml

fixed grammatical errors

---

main.py

This pull request includes updates to the `main.py` file to fix the issue #528.
Codebase simplification:
* [`main.py`](diffhunk://#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L11-R11): Added `StyleManager` to the import list from `lib_resume_builder_AIHawk`.
* [`main.py`](diffhunk://#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L161-R161): Modified the `init_browser` function to directly instantiate `StyleManager` instead of accessing it through `FacadeManager`.

fix: issue #528

---

README.md
main.py
src/aihawk_bot_facade.py
src/aihawk_job_manager.py

This is a suggestion of feature that I've created to only collect data from job offers.  I consider useful to identify IT Industry market trends.
Best regards

Creating the '--collect' parameter to just collect jobs information

---

src/aihawk_job_manager.py

Fix this issue: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/552

encode position. otherwise "C++ engineer" wouldn't work

---

src/aihawk_easy_applier.py

This PR fixes the following issue:
https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/564
Takes into account the current job's company name before saving the answer to answers.json. If the current job's company name exists within the answer, the answer will not be saved to answers.json. Previous company's names will not be saved to answers.json now. Users will probably have to go through their answers.json file and purge offending answers.

fix issue #564. Company name is saved in answers.json.

---

README.md

- extra spaces, lines
- inconsistent header numbering
- replace inline html with markdown
- fix up bad links
- bare URLs

fix README.md markdown linting errors

---

data_folder/config.yaml
data_folder_example/config.yaml
main.py
src/aihawk_job_manager.py

1. Changed key names from 'companyBlacklist' and 'titleBlacklist' to 'company_blacklist' and 'title_blacklist'
2. Added location blacklist feature to avoid applying for jobs in specific location(s)
3. Added 'location_blacklist' to the default config.yaml

Add location blacklist feature.

---

src/llm/llm_manager.py

changed return type to str so it can be read properly when iterating thru answers.json

fixed int not iterable issue

---

src/aihawk_job_manager.py

🔀[src/aihawk_job_manager.py] skip previously failed jobs

---

README.md
data_folder/config.yaml
data_folder_example/config.yaml
src/aihawk_job_manager.py

Fixed Issue #551, right now user can add more filter in url like "Remote, Hybrid and On-site". Also update the readme document and config.yaml in both data_folder folder and data_folder_example.

Fixed Issue #551, user can add more filter in url like "Remote, Hybrid and On-site"

---

src/aihawk_easy_applier.py

Reverts feder-cr/Auto_Jobs_Applier_AIHawk#609
code was hard coded to set 0 , its wrong,

Revert "🔀[src/aihawk_easy_applier.py] answers 0 to "years of experience" unle…"

---

src/ai_hawk/job_manager.py

Fixed Bugs mentioned in issues #630. Change commit #3673556.

Fixed Bugs mentioned in issues #630

---

src/ai_hawk/linkedIn_easy_applier.py

Synchronization of main stream PR #623, important bug fixes.

Synchronization of main stream PR #623, important bug fixes.

---

README.md

Synchronizing important changes on the main branch. Update the gemini api url

Synchronizing important changes on the main branch

---

README.md

Update README.md for developer

Update README.md for developer

---

src/ai_hawk/llm/llm_manager.py
src/strings.py

- This PR fixes #686 where it skips jobs that are suitable
- Better prompt to force LLM output the required response
- It cleans the output from LLM to properly parse using regex

Fix #686 Bug when parsing job suitability result

---

data_folder/config.yaml
main.py
src/aihawk_job_manager.py

change 'experienceLevel' to 'experience_level' to match config.yaml otherwise desired experience wasn't filtered

bug: change 'experience_level' to 'experienceLevel'

---

README.md

Compared to a Python virtual environment, Conda is easier to use.

Add Conda description #737

---

README.md
data_folder_example/config.yaml

Fixes #749 
- `config.yaml` in data_folder_example and the data folder now both have consistent schema
- ReadMe updated to be consistent with above changes

Fix consistency in docs

---

.github/workflows/label_release.yml
data_folder_example/config.yaml

Feature: Adds CI pipeline to auto label PRs merged to release branches. Adds `merged-to-release` label

bug: docs inconsistency FIx

---

src/logging.py

Both Selenium logs and the logger were being written to app.log. This commit resolves the issue by separating them into two files, with support for compression and scheduled deletion。

Fixed the issue of multiple logs writing to the same file. #778

---

.gitignore
README.md
config.py
constants.py
data_folder/work_preferences.yaml
data_folder_example/work_preferences.yaml
main.py
src/ai_hawk/job_manager.py
src/ai_hawk/llm/llm_manager.py

renamed config.yaml to work_preferences.yaml. moved irrelavent prev config to config.py

Ft config code refactoring

---

data_folder/work_preferences.yaml

removed unsed config in work_preferences.yaml
a missed delta from my previous PR

removed missed config change

---

README.md

Included links to AI/ML API docs and the endpoint to be used in the code.

Add AI/ML API info

---

src/ai_hawk/job_manager.py

Feature Summary: Log timestamp in success, failed, skipped and data JSON files
Motivation: The user should be able to see when the job is applied for, or when the request was failed etc.

[FEATURE] Log time in success, failed, skipped and data json files

---

src/ai_hawk/job_manager.py

fixes [BUG]: Not applying to jobs #919

---

README.md

Fix the typo in the `README.md`
Fixing issue: https://github.com/AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent/issues/969

[969] [DOCS] improve the README

---

requirements.txt

Ft job portal refactoring

---

main.py

There was a duplicate line initializing the StyleManager

Fix duplicate line
