feder-cr/Jobs_Applier_AI_Agent_AIHawk

- linkedIn_job_manager.py
This PR fixes an issue in the get_base_search_url method where all experience levels were being included in the job search URL, regardless of user preferences.
This change:
1. Iterates through the 'experienceLevel' dictionary in the parameters
2. Only includes levels where the corresponding value is True
3. Correctly maps the index to LinkedIn's experience level values (1-6)
The job search URL will now accurately reflect the user's selected experience levels from the config.yaml file.
> Fix: Updated get_base_search_url to correctly apply user's experienceLevel preferences.

- src/linkedIn_authenticator.py
Make the function better, because is not needed check selectors. when a user is logged on linkedin will be redirected already on /feed/ endpoint, otherwise url will remain https://linkedin.com, so is possible check the state of login just using this approach
> logged in functions optimized

- src/gpt.py
There is an issue with how the bot processes the response from the answer_question_textual_wide_range method. The response is not being handled properly because it doesn't match the expected format for section names. The bot expects a simple string, such as "Personal Information," for the section name. However, the response (especially from the CosmosRP model) includes additional text and formatting that are not being stripped away.
To address this, a regular expression is implemented to match only the exact section names from the expected list. This ensures that any extraneous text is ignored and only the relevant section name is extracted. If no match is found, a ValueError is raised to flag any deviations in the response format.
> Fix Section Name Parsing Issue in answer_question_textual_wide_range Method

- README.md
- data_folder/config.yaml
- data_folder_example/config.yaml
- src/linkedIn_job_manager.py
This pull request adds a new configuration option to control the job application process. The `applyOnceAtCompany` parameter allows users to specify whether they want to apply only once per company (`True` or `False`), preventing multiple applications to the same company. Additionally, a new feature ensures that users will not apply to the same job twice, based on the job link.
Changes include:
- Added `applyOnceAtCompany` option in the `config.yaml` file.
- Updated the `LinkedInJobManager` class to include logic that skips jobs where the user has already applied.
- Two new functions:
1. `is_already_applied_to_job`: Checks if the user has already applied to the specific job.
2. `is_already_applied_to_company`: Verifies if the user has already applied to a job at the same company, based on …
> Add configuration to apply once per job and once per company based on user settings

- .gitignore
- app_config.py
- main.py
- src/utils.py
- tests/test_linkedIn_job_manager.py
> YAML Validations for config.py

- data_folder/config.yaml
- requirements.txt
- src/llm/llm_manager.py
Added Support for HuggingFace API and Model Handling, Updated Parsing Logic
-Introduced two new classes: HuggingFaceEndpoint (for API calls) and ChatHuggingFace (for model interaction)
-Adjusted the parse_llmresult method in the LoggerChatModel class because of the different response formats returned by ChatHuggingFace models compared to other proprietary models like ChatAnthropic or ChatOpenAI  (still requires further change )
-The specific model type and ID in use can be found in the config.yaml file
> Add Hugging API

- src/linkedIn_job_manager.py
Origin Element will crawl the job title twice since LinkedIn has a hidden tag in this section.
The result will be like blowing screenshot. (duplicate job tile )
only get the text value in `strong` tag
> Fix: job title crawl issue

- README.md
- src/aihawk_easy_applier.py
Updated README to contain the appropriate style for apply_once_at_company. This should also address one of the items in my enhancements issue #424
> fix: Update README.md to use apply_once_at_company style

- README.md
- assets/resume_schema.yaml
- data_folder/plain_text_resume.yaml
- data_folder_example/plain_text_resume.yaml
This PR addresses the issue of missing zip codes in addresses by implementing the following changes:
-     Added a field to include zip codes in the address format where applicable.
-     Updated any address-related functions and data structures to support zip code inclusion.
-     Refactored existing code to ensure compatibility with the new zip code field.
These changes should ensure that the bot now fully supports addresses with zip codes
> Added Zipcode to Addresses in Auto Jobs Applier (#407)  Issue Resolved: #407

- src/aihawk_job_manager.py
- src/extractors/extraction_chains.py
- tests/test_aihawk_job_manager.py
So this introduces a concept of "extraction chains" for our job parsing. Certain issues: (https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/114) are happening because there are parsing changes necessary when LinkedIn changes something on their end. Instead of changing our parsing code each time, we can add a new parser here when we encounter some new linkedin HTML format.
Shoutout to @pafthinder for his initial correct implementation which I've included here. This fixes THAT issue and fixes issues I had been having myself.
> extraction chains

- src/aihawk_easy_applier.py
added detection for country code field which was previously defaulted to first option element under the select element
> added detection for country code field which was previously defaulted to first option element under the select element

- src/aihawk_easy_applier.py
fixed #557
`class AIHawkEasyApplier`'s `_save_questions_to_json()` method now checks if the question has already been saved with an answer, and aborts the new save request if so. Preventing duplicated of the same question being saved.
> 🔀[aihawl_easy_applier.py] fixed saving duplicate questions to answers.json

- src/aihawk_easy_applier.py
Fix for issue https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/457:
When user is a LinkedIn premium user, the description is not found. See issue 457 for examples. The proposed fix first checks for the original class name used in non premium LinkedIn and if the element is not found then it searches for the Premium version of  LinkedIn's class name. Tested with my Premium version of LinkdIn and it works. Also proposing this gets merged to v4 obviously which also has the same bug here:
https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/blob/dceae26382bb8a931c43bc3e574414e57c29722a/src/aihawk_easy_applier.py#L374
> fix issue: #457. Premium user's can't find descriptions.

- src/aihawk_job_manager.py
This commit fixes an issue where blacklist checks for job titles were case-sensitive. Now, job titles are compared in lowercase to ensure correct matches regardless of uppercase or lowercase usage. The map(str.lower, ...) function was added to convert blacklist words for job titles to lowercase, ensuring consistent comparison.
Additionally, excessive HTML logs are making it difficult to debug the application effectively, which should be addressed in future commits to improve clarity during debugging.
> Fix case sensitivity in blacklist comparisons for job titles

- .gitignore
- app_config.py
- main.py
- src/ai_hawk/authenticator.py
- src/ai_hawk/bot_facade.py
- src/ai_hawk/job_manager.py
- src/ai_hawk/linkedIn_easy_applier.py
- src/ai_hawk/llm/llm_manager.py
- src/job.py
- src/job_application_profile.py
- src/logging.py
- src/utils.py
- tests/test_aihawk_job_manager.py
- tests/test_utils.py
- implements /log/app.log
- app_config.py has new vars
- LOG_TO_FILE
- LOG_TO_CONSOLE
-  thread pooling fixes to support file logging
- to support the PR #555
> file based logging

- src/aihawk_job_manager.py
This is an urgent fix because the absence of the failed.json file prevents the script from running. The issue has already been fixed in the release branch. Now, we are urgently syncing it to the main branch.
> Urgent fix issue in #648

- main.py
Fixes issue #681 
- If resume is provided with flag `--resume`, it will not ask to select resume style and upload the provided resume.
- If resume is not provided, it runs as usual.
> Fixes #681

- src/ai_hawk/job_manager.py
- tests/test_aihawk_job_manager.py
With the merge of PR #671 the `get_base_search_url` in `AIHawkJobManager` broke because the updated date mappings were not incorporated in the function. As a result, the function was unable to build the correct base query and defaulted to searching for jobs posted "all time."
- Updated the `date_mapping` object to utilize the new YAML values, which rectifies the function to build the query as intended.
Tested on local and is working as expected.
> Hotfix - Fix get_base_search_url method to build valid date query

- CONTRIBUTING.md
- docs/development_diagrams.md
- branch rules
- release process
- roles
- semver
- diagrams
> contributing updates

- src/ai_hawk/job_manager.py
Fixed Issue #737, add Skip, Failed reason
> Feature:  add Skip, Failed reason

- src/ai_hawk/linkedIn_easy_applier.py
Feature #789 
- If it fails applying for a job, it saves the progress to My Jobs, In progress section
- Allows users to complete the application for that job at a later time
- It will only start applying for a job if you're suitable, so if it fails to answer a form/question, it makes sense to save the progress instead of discarding the process.
> Save job application process after failure

- src/ai_hawk/llm/llm_manager.py
Fixes: #868
- Upon logs inspection my LLM (gemini) was outputting something like: 
```
Score: 8
Reasoning:This is because ...
```
with no space after the `Reasoning:` part which was throwing error because regex could not find a matching group.
- This introduces better handling of regex pattern to make it robust.
> Fix job suitability

- src/ai_hawk/llm/prompts.py
Some providers (as OpenAI) support reducing cost of calls by caching repetitive content, but the feature works only with the initial portion (prefix) of prompts.
Keeping repetitive content in the beginning improves caching and reducing costs.
The only change is swap of "My resume" and "Job Description" sections to keep repetitive part first
[OpenAI doc](https://platform.openai.com/docs/guides/prompt-caching)
P.S.
No effect on response is assumed but not tested
> perf: :zap: Optimize prompt for better caching

- src/ai_hawk/job_manager.py
This PR fixes the following error:
```
Traceback (most recent call last):
File "/home/anders/Project/Auto_Jobs_Applier_AIHawk/main.py", line 27, in <module>
from ai_hawk.job_manager import AIHawkJobManager
File "/home/anders/Project/Auto_Jobs_Applier_AIHawk/src/ai_hawk/job_manager.py", line 8, in <module>
from turtle import color
File "/usr/lib/python3.12/turtle.py", line 101, in <module>
import tkinter as TK
ModuleNotFoundError: No module named 'tkinter'
```
by removing the import statement `from turtle import color` from the file, which can be done as the import statement is not being used.
I'm on WSL2 by the way.
> Remove unused import statement as it causes tkinter error

- README.md
Corrected the git clone URL and cd directory name in the Clone the repository section of the README.md file.
Changes made:
Updated the incorrect git clone URL from:
```
git clone https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk.git
cd Auto_Jobs_Applier_AIHawk
```
****
to the correct one:
```
git clone https://github.com/code-infected/Auto_Jobs_Applier_AI_Agent.git
cd Auto_Jobs_Applier_AI_Agent
```
> Fix git clone URL and cd directory in README.md

- README.md
Previously, I mistakenly updated the README with the wrong repository link and directory name. This fixes those errors by providing the correct details.
> Replaced wrong repo link and directory name

- README.md
Remove feature link from table of contents, since there is no feature section for now
> Remove feature from table of contents
